### ISSUE TITLE
footer at bottom of page

### ISSUE THREAD

**Issue by jer3m01** [NamelessMC/Nameless#1013]
could you add in default theme the footer is at the bottom of the page? (not being fixed to the bottom of the window) 
i have done it on https://amnesia-network.com here is the code i used: 
```CSS
/* new */
*,
*:before,
*:after {
  box-sizing: inherit;
}

html{
    font-family:sans-serif;
    -ms-text-size-adjust:100%;
    -webkit-text-size-adjust:100%;
    height: 100%;
    box-sizing: border-box;
}
body{
    min-height: 100%;
    position: relative;
    margin:0;
    padding-bottom: 8rem;
}
/* new 
* btw added class= "footer" in footer div 
* think you already knew
*/

.footer {
   bottom: 0;
   position: absolute;
   width: 100%;
}
```
