### ISSUE TITLE
Duplicate placeholders

### ISSUE THREAD

**Issue by RobiNN1** [NamelessMC/Nameless#2322]
If you allow a placeholders, it always add the same placeholder on every request.

- Tested on localhost
- MC 1.16
- plugin is compiled from latest version on Github
- Nameless is also latest version from Github
- PHP 8.0.7, MariaDB 10.5.10

Also I enabled only first placeholder.

```yml
# Nameless Plugin configuration

# For example http(s)://yoursite.com/index.php?route=/api/v2/API_KEY
# Enable the API and obtain the API URL in StaffCP > Configuration > API
# After setting this, you need to do a full server restart, because the plugin's reload command won't work.
api-url: "http://nameless.host/index.php?route=/api/v2/mzCrMn0cu8IgR6iUPpDXJtAjwYNdyEql"

# Enter this if you wish for the plugin to send data about this server
# and its players to the website. This is required for username and rank synchronisation.
# You can find this in StaffCP > Integrations > Minecraft > Minecraft Servers
server-id: 1

# This feature sends information about the server and online players to
# your NamelessMC website. This value is in seconds. Increase to lower
# the frequency that data is sent. Decrease to send data more frequently.
# Setting this too low can cause lag. Set to 0 to disable.
server-data-upload-rate: 10

# You can add PlaceholderAPI placeholders here, they will be sent to the website to be used by NamelessMC or modules.
# The placeholders can be global or player-specific
# This option is unrelated to the "enable-placeholders" option
upload-placeholders:
  enabled: true
  # global placeholders to send to the website (list of placeholder names without %%). Currently not used by the website.
  global: []
  # player-specific placeholders to send to the website (list of placeholder names without %%)
  player:
    - player_gamemode


# Enable PlaceholderAPI and MVdWPlaceholderAPI placeholders
# This will increase traffic to your NamelessMC website (depending on placeholders-request-delay)
# This option will be ignored if PlaceholderAPI and MVdWPlaceholderAPI are not installed
enable-placeholders: true

# Number of milliseconds in between notifications request
# Lower number means more frequent updates of placeholders, but higher
# network usage.
placeholders-request-delay: 2000

# Turn on debug mode for the underlying NamelessMC Java API
api-debug-mode: true

# Send a message to players who don't have a NamelessMC account when they join
not-registered-join-message: false

# For a list of valid languages, check file names in the 'languages' directory.
# To help translate the plugin to your language, visit https://translate.namelessmc.com
# If you want to customize messages for your server you can edit the language files.
# WARNING: The language file will be replaced with the default when new messages are added in a plugin update
language: en_UK

# Auto whitelist registered players.
#
# When enabled, the plugin will automatically whitelist players that are registered on the website.
# Warning: Anyone who is not registered on the website will be removed from the whitelist, also
# if they were added before enabling this option!
# By default, the plugin will poll the website every 5 minutes to get a list of registered users.
# You need to fully restart the server after changing this option.
auto-whitelist-registered:
  enabled: false
  # Only whitelist player if their account is verified
  verified: true
  # Number of seconds to wait in between updating the whitelist
  poll-interval: 30
  # Send log messages when whitelisting or unwhitelisting users
  log: true
  # List of UUIDs to exlude (never add to or remove from the whitelist)
  exclude: []


```

![screen](https://user-images.githubusercontent.com/11664877/124467398-190d4680-dd98-11eb-80f6-7b3bbdcb84f8.png)
![124467404-1b6fa080-dd98-11eb-8d84-1f2880f5af2d](https://user-images.githubusercontent.com/11664877/124509095-9608e200-ddd1-11eb-8a49-7dc263236e1e.png)
