### ISSUE TITLE
Admin Panel Menu Toggled

### ISSUE THREAD

**Issue by TeemoCell** [NamelessMC/Nameless#2481]
### Describe the issue

You can't change the menu type when toggled.

### NamelessMC Version

2.0.0-pr12

### To Reproduce

1. Go to your admin panel
2. Click on 
![image](https://user-images.githubusercontent.com/11705513/140193143-109cbe20-de54-4ee5-9fb3-4d0e8ca76de5.png)

### Expected Behaviour

...

### Screenshots

This is the toggled state.
![image](https://user-images.githubusercontent.com/11705513/140192408-47405e7e-64b3-43ab-8618-70f94bcd686b.png)
You have to zoom out to view the button.
![image](https://user-images.githubusercontent.com/11705513/140193032-60adc7d2-9cc3-440f-aaa4-fc34952b8821.png)

### Additional Information

How to fix this?!

Add this code to `custom.css` in `custom/panel_templates/Default/assets/css`
```css
.sidebar.toggled {
    overflow: visible;
    overflow-x: hidden;
    overflow-y: auto;
    scrollbar-width: none;
}
```
This allows you scroll when you toggled the menu but the scrollbar is hidden.
