### ISSUE TITLE
@mentions do not work for nicknames with spaces in them

### ISSUE THREAD

**Issue by tadhgboyle** [NamelessMC/Nameless#3315]
![image](https://user-images.githubusercontent.com/26070412/232172553-c6b7902c-e083-46f6-8558-4181a40cb232.png)
<img width="764" alt="image" src="https://user-images.githubusercontent.com/26070412/232172567-57675273-d69e-46f7-bc7a-c6b635e4e594.png">
<img width="799" alt="image" src="https://user-images.githubusercontent.com/26070412/232172576-6b0e917b-9db1-4a84-bc8f-588ead5febd5.png">

Also, when doing this fix, add this css to `custom.css` for nicer mention tags:
```css
.user-mention {
    background: #e7edf3;
    padding: 2px 5px;
    border-radius: 3px;
    font-weight: bold;
}
```
