### ISSUE TITLE
[Suggestion] Switch from <style> tags to root/body classes

### ISSUE THREAD

**Issue by CallMeMantas** [NamelessMC/Nameless#474]
Theming with `<style>` for custom pages is an OK solution, but it’s a bit clunky and could be improved by simply using root (`<html>` or `<body>`) classes instead.

With this approach, you can detect what page you’re in with CSS & JavaScript, take advantage of Sass, and the CSS is loaded alongside everything else on load. The source code looks cleaner! Just take a look at this comparison:

## With `<style>` tags

```html
<body class="play">
  <div class="join">
     <p>The IP is <strong>play.example.com</strong>!</p>
…
```

And in a separate file…

```css
.join {
      padding: 1rem;
      background: rgba(dodgerblue, 0.6);
      color: #fff;
      & strong { font-style: italic; }
}
```

## With root classes

```html
<body>
  <style>
     .join {
      padding: 1rem;
      background: rgba(30, 144, 255, 0.6);
      color: #fff;
    }
    .join strong { font-style: italic; }
  </style>
  <div class="join">
     <p>The IP is <strong>play.example.com</strong>!</p>
…
```
